// This file is automatically generated by qtc from "product.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line examples/shopo/templates/product.qtpl:1
package templates

//line examples/shopo/templates/product.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line examples/shopo/templates/product.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line examples/shopo/templates/product.qtpl:1
func StreamProductWidget(qw422016 *qt422016.Writer, product *Product) {
	//line examples/shopo/templates/product.qtpl:1
	qw422016.N().S(`
  <div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
      <img src="http://placehold.it/320x150" alt="">
      <div class="caption">
        <h4 class="pull-right">`)
	//line examples/shopo/templates/product.qtpl:6
	qw422016.E().S(product.Price)
	//line examples/shopo/templates/product.qtpl:6
	qw422016.N().S(`</h4>
        <h4><a href="#">`)
	//line examples/shopo/templates/product.qtpl:7
	qw422016.E().S(product.Name)
	//line examples/shopo/templates/product.qtpl:7
	qw422016.N().S(`</a>
        </h4>
        <p>`)
	//line examples/shopo/templates/product.qtpl:9
	qw422016.E().S(product.Description)
	//line examples/shopo/templates/product.qtpl:9
	qw422016.N().S(`</p>
      </div>
      <input type="button" class="btn btn-success" value="Add to Cart" id="add-`)
	//line examples/shopo/templates/product.qtpl:11
	qw422016.E().S(product.ID)
	//line examples/shopo/templates/product.qtpl:11
	qw422016.N().S(`"/>
    </div>
  </div>
`)
//line examples/shopo/templates/product.qtpl:14
}

//line examples/shopo/templates/product.qtpl:14
func WriteProductWidget(qq422016 qtio422016.Writer, product *Product) {
	//line examples/shopo/templates/product.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line examples/shopo/templates/product.qtpl:14
	StreamProductWidget(qw422016, product)
	//line examples/shopo/templates/product.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line examples/shopo/templates/product.qtpl:14
}

//line examples/shopo/templates/product.qtpl:14
func ProductWidget(product *Product) string {
	//line examples/shopo/templates/product.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line examples/shopo/templates/product.qtpl:14
	WriteProductWidget(qb422016, product)
	//line examples/shopo/templates/product.qtpl:14
	qs422016 := string(qb422016.B)
	//line examples/shopo/templates/product.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line examples/shopo/templates/product.qtpl:14
	return qs422016
//line examples/shopo/templates/product.qtpl:14
}
