// This file is automatically generated by qtc from "products.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line examples/shopo/templates/products.qtpl:1
package templates

//line examples/shopo/templates/products.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line examples/shopo/templates/products.qtpl:1
import "github.com/yanzay/teslo/templates"

//line examples/shopo/templates/products.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line examples/shopo/templates/products.qtpl:3
func StreamPage(qw422016 *qt422016.Writer, state State) {
	//line examples/shopo/templates/products.qtpl:3
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="static/css/shop-homepage.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="app">
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Shop Name</p>
                `)
	//line examples/shopo/templates/products.qtpl:69
	StreamCartWidget(qw422016, state.Cart.Items)
	//line examples/shopo/templates/products.qtpl:69
	qw422016.N().S(`
                <div class="list-group">
                    <a href="#" class="list-group-item">Category 1</a>
                    <a href="#" class="list-group-item">Category 2</a>
                    <a href="#" class="list-group-item">Category 3</a>
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row" id="products">
                    `)
	//line examples/shopo/templates/products.qtpl:111
	for _, product := range state.Products {
		//line examples/shopo/templates/products.qtpl:111
		qw422016.N().S(`
                      `)
		//line examples/shopo/templates/products.qtpl:112
		StreamProductWidget(qw422016, product)
		//line examples/shopo/templates/products.qtpl:112
		qw422016.N().S(`
                    `)
		//line examples/shopo/templates/products.qtpl:113
	}
	//line examples/shopo/templates/products.qtpl:113
	qw422016.N().S(`
                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    `)
	//line examples/shopo/templates/products.qtpl:139
	templates.StreamJS(qw422016)
	//line examples/shopo/templates/products.qtpl:139
	qw422016.N().S(`

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>

</body>

</html>
`)
//line examples/shopo/templates/products.qtpl:147
}

//line examples/shopo/templates/products.qtpl:147
func WritePage(qq422016 qtio422016.Writer, state State) {
	//line examples/shopo/templates/products.qtpl:147
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line examples/shopo/templates/products.qtpl:147
	StreamPage(qw422016, state)
	//line examples/shopo/templates/products.qtpl:147
	qt422016.ReleaseWriter(qw422016)
//line examples/shopo/templates/products.qtpl:147
}

//line examples/shopo/templates/products.qtpl:147
func Page(state State) string {
	//line examples/shopo/templates/products.qtpl:147
	qb422016 := qt422016.AcquireByteBuffer()
	//line examples/shopo/templates/products.qtpl:147
	WritePage(qb422016, state)
	//line examples/shopo/templates/products.qtpl:147
	qs422016 := string(qb422016.B)
	//line examples/shopo/templates/products.qtpl:147
	qt422016.ReleaseByteBuffer(qb422016)
	//line examples/shopo/templates/products.qtpl:147
	return qs422016
//line examples/shopo/templates/products.qtpl:147
}
