// This file is automatically generated by qtc from "base.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/base.qtpl:1
package templates

//line templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// All the text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.
//
// Hello is a simple template function.

//line templates/base.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base.qtpl:5
func StreamHello(qw422016 *qt422016.Writer, name string) {
	//line templates/base.qtpl:5
	qw422016.N().S(`
<html>
<head>
<title>Test title</title>
<script>
window.addEventListener("load", function(evt) {
  var ws = new WebSocket("ws://localhost:8080/ws");
  ws.onopen = function(e) {
    document.write("OPEN");
  };
  ws.onclose = function(e) {
    document.write("CLOSE");
  };
  ws.onmessage = function(e) {
    document.write(e.data);
  };
  ws.onerror = function(e) {
    document.write("Error: ", e.data);
  };
});
</script>
</head>
<body>
    <p>Hello, `)
	//line templates/base.qtpl:28
	qw422016.E().S(name)
	//line templates/base.qtpl:28
	qw422016.N().S(`!</p>
</body>
</html>
`)
//line templates/base.qtpl:31
}

//line templates/base.qtpl:31
func WriteHello(qq422016 qtio422016.Writer, name string) {
	//line templates/base.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/base.qtpl:31
	StreamHello(qw422016, name)
	//line templates/base.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:31
}

//line templates/base.qtpl:31
func Hello(name string) string {
	//line templates/base.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/base.qtpl:31
	WriteHello(qb422016, name)
	//line templates/base.qtpl:31
	qs422016 := string(qb422016.B)
	//line templates/base.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/base.qtpl:31
	return qs422016
//line templates/base.qtpl:31
}
