// This file is automatically generated by qtc from "base.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/base.qtpl:1
package templates

//line templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// All the text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.
//
// Hello is a simple template function.
//

//line templates/base.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base.qtpl:6
func StreamHello(qw422016 *qt422016.Writer, name string) {
	//line templates/base.qtpl:6
	qw422016.N().S(`
<html>
<head>
<title>Test title</title>
<script>
window.addEventListener("load", function(evt) {
  var ws = new WebSocket("ws://localhost:8080/ws");
  ws.onopen = function(e) {
    console.log("OPEN");
  };
  ws.onclose = function(e) {
    console.log("CLOSE");
  };
  ws.onmessage = function(e) {
    var message = JSON.parse(e.data);
    var el = document.getElementById(message.id)
    el.innerHTML = message.content;
  };
  ws.onerror = function(e) {
    console.log("Error: ", e.data);
  };
});
</script>
</head>
<body id="app">
    `)
	//line templates/base.qtpl:31
	StreamBody(qw422016, name)
	//line templates/base.qtpl:31
	qw422016.N().S(`
</body>
</html>
`)
//line templates/base.qtpl:34
}

//line templates/base.qtpl:34
func WriteHello(qq422016 qtio422016.Writer, name string) {
	//line templates/base.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/base.qtpl:34
	StreamHello(qw422016, name)
	//line templates/base.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:34
}

//line templates/base.qtpl:34
func Hello(name string) string {
	//line templates/base.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/base.qtpl:34
	WriteHello(qb422016, name)
	//line templates/base.qtpl:34
	qs422016 := string(qb422016.B)
	//line templates/base.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/base.qtpl:34
	return qs422016
//line templates/base.qtpl:34
}

//line templates/base.qtpl:36
func StreamBody(qw422016 *qt422016.Writer, name string) {
	//line templates/base.qtpl:36
	qw422016.N().S(`
  <p>Hello, `)
	//line templates/base.qtpl:37
	qw422016.E().S(name)
	//line templates/base.qtpl:37
	qw422016.N().S(`!</p>
`)
//line templates/base.qtpl:38
}

//line templates/base.qtpl:38
func WriteBody(qq422016 qtio422016.Writer, name string) {
	//line templates/base.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/base.qtpl:38
	StreamBody(qw422016, name)
	//line templates/base.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:38
}

//line templates/base.qtpl:38
func Body(name string) string {
	//line templates/base.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/base.qtpl:38
	WriteBody(qb422016, name)
	//line templates/base.qtpl:38
	qs422016 := string(qb422016.B)
	//line templates/base.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/base.qtpl:38
	return qs422016
//line templates/base.qtpl:38
}
