// This file is automatically generated by qtc from "js.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/js.qtpl:1
package templates

//line templates/js.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/js.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/js.qtpl:1
func StreamJS(qw422016 *qt422016.Writer) {
	//line templates/js.qtpl:1
	qw422016.N().S(`
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
`)
	//line templates/js.qtpl:4
	qw422016.N().S(`window.addEventListener("load", function(evt) {
  var ws = new WebSocket("ws://localhost:8080/ws");
  ws.onopen = function(e) {
    console.log("OPEN");
  };
  ws.onclose = function(e) {
    console.log("CLOSE");
  };
  ws.onmessage = function(e) {
    var message = JSON.parse(e.data);
    var el = document.getElementById(message.id)
    el.outerHTML = message.content;
  };
  ws.onerror = function(e) {
    console.log("Error: ", e.data);
  };
  var app = document.getElementById("app");

  var parentIds = function(el) {
    return $(el).parents().map(function(i, el) {return el.id;}).toArray().filter(function(id) {return id !== ""});
  };

  var clickHandler = function(e) {
    console.log("Click handler");
    console.log(e.target.id);
    console.log(parentIds);
    if (e.target.id) {
      ws.send(JSON.stringify({event: "click", id: e.target.id, parents: parentIds(e.target)}));
    }
  };
  var submitHandler = function(e) {
    console.log("Submit handler");
    e.preventDefault();
    var form = $(e.target).serialize();
    console.log($(e.target));
    console.log(form);
    var resp = {
      event: "submit",
      id: e.target.id,
      data: form,
    };
    console.log(resp);
    ws.send(JSON.stringify(resp));
  };
  var changeHandler = function(e) {
    console.log("Change handler");
    console.log(e.target);
    console.log($(e.target));
    console.log($(e.target).data());
    console.log(e.target.checked);
    if (e.target.checked !== undefined) {
      var data = $(e.target).data();
      data.checked = e.target.checked;
      var resp = {
        event: "change",
        parents: parentIds(e.target),
        data: JSON.stringify($(e.target).data())
      };
      ws.send(JSON.stringify(resp));
    }
  };
  app.addEventListener("click", clickHandler);
  app.addEventListener("submit", submitHandler);
  app.addEventListener("change", changeHandler);
});

`)
	//line templates/js.qtpl:4
	qw422016.N().S(`
</script>
`)
//line templates/js.qtpl:6
}

//line templates/js.qtpl:6
func WriteJS(qq422016 qtio422016.Writer) {
	//line templates/js.qtpl:6
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/js.qtpl:6
	StreamJS(qw422016)
	//line templates/js.qtpl:6
	qt422016.ReleaseWriter(qw422016)
//line templates/js.qtpl:6
}

//line templates/js.qtpl:6
func JS() string {
	//line templates/js.qtpl:6
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/js.qtpl:6
	WriteJS(qb422016)
	//line templates/js.qtpl:6
	qs422016 := string(qb422016.B)
	//line templates/js.qtpl:6
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/js.qtpl:6
	return qs422016
//line templates/js.qtpl:6
}
