// This file is automatically generated by qtc from "message.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/message.qtpl:1
package templates

//line templates/message.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/message.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/message.qtpl:2
func StreamMessage(qw422016 *qt422016.Writer, id string, content string) {
	//line templates/message.qtpl:2
	qw422016.N().S(`{"id":`)
	//line templates/message.qtpl:3
	qw422016.N().Q(id)
	//line templates/message.qtpl:3
	qw422016.N().S(`,"content":`)
	//line templates/message.qtpl:3
	qw422016.N().Q(content)
	//line templates/message.qtpl:3
	qw422016.N().S(`}`)
//line templates/message.qtpl:4
}

//line templates/message.qtpl:4
func WriteMessage(qq422016 qtio422016.Writer, id string, content string) {
	//line templates/message.qtpl:4
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/message.qtpl:4
	StreamMessage(qw422016, id, content)
	//line templates/message.qtpl:4
	qt422016.ReleaseWriter(qw422016)
//line templates/message.qtpl:4
}

//line templates/message.qtpl:4
func Message(id string, content string) string {
	//line templates/message.qtpl:4
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/message.qtpl:4
	WriteMessage(qb422016, id, content)
	//line templates/message.qtpl:4
	qs422016 := string(qb422016.B)
	//line templates/message.qtpl:4
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/message.qtpl:4
	return qs422016
//line templates/message.qtpl:4
}
