// This file is automatically generated by qtc from "base.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line cmd/templates/base.qtpl:1
package templates

//line cmd/templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line cmd/templates/base.qtpl:1
import "github.com/yanzay/teslo/templates"

//line cmd/templates/base.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line cmd/templates/base.qtpl:4
type Item struct {
	ID      string
	Content string
	Done    bool
}

type State struct {
	Items []*Item
}

//line cmd/templates/base.qtpl:15
func StreamPage(qw422016 *qt422016.Writer, state State) {
	//line cmd/templates/base.qtpl:15
	qw422016.N().S(`
<html>
<head>
<title>Test title</title>
`)
	//line cmd/templates/base.qtpl:19
	templates.StreamJS(qw422016)
	//line cmd/templates/base.qtpl:19
	qw422016.N().S(`
</head>
<body id="app">
    `)
	//line cmd/templates/base.qtpl:22
	StreamTodo(qw422016, state.Items)
	//line cmd/templates/base.qtpl:22
	qw422016.N().S(`
</body>
</html>
`)
//line cmd/templates/base.qtpl:25
}

//line cmd/templates/base.qtpl:25
func WritePage(qq422016 qtio422016.Writer, state State) {
	//line cmd/templates/base.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line cmd/templates/base.qtpl:25
	StreamPage(qw422016, state)
	//line cmd/templates/base.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line cmd/templates/base.qtpl:25
}

//line cmd/templates/base.qtpl:25
func Page(state State) string {
	//line cmd/templates/base.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line cmd/templates/base.qtpl:25
	WritePage(qb422016, state)
	//line cmd/templates/base.qtpl:25
	qs422016 := string(qb422016.B)
	//line cmd/templates/base.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line cmd/templates/base.qtpl:25
	return qs422016
//line cmd/templates/base.qtpl:25
}

//line cmd/templates/base.qtpl:27
func StreamBody(qw422016 *qt422016.Writer, name string) {
	//line cmd/templates/base.qtpl:27
	qw422016.N().S(`
  <p>Hello, `)
	//line cmd/templates/base.qtpl:28
	qw422016.E().S(name)
	//line cmd/templates/base.qtpl:28
	qw422016.N().S(`!</p>
`)
//line cmd/templates/base.qtpl:29
}

//line cmd/templates/base.qtpl:29
func WriteBody(qq422016 qtio422016.Writer, name string) {
	//line cmd/templates/base.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line cmd/templates/base.qtpl:29
	StreamBody(qw422016, name)
	//line cmd/templates/base.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line cmd/templates/base.qtpl:29
}

//line cmd/templates/base.qtpl:29
func Body(name string) string {
	//line cmd/templates/base.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
	//line cmd/templates/base.qtpl:29
	WriteBody(qb422016, name)
	//line cmd/templates/base.qtpl:29
	qs422016 := string(qb422016.B)
	//line cmd/templates/base.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
	//line cmd/templates/base.qtpl:29
	return qs422016
//line cmd/templates/base.qtpl:29
}

//line cmd/templates/base.qtpl:31
func StreamTodo(qw422016 *qt422016.Writer, items []*Item) {
	//line cmd/templates/base.qtpl:31
	qw422016.N().S(`
<ul id="todo">
  `)
	//line cmd/templates/base.qtpl:33
	for _, item := range items {
		//line cmd/templates/base.qtpl:33
		qw422016.N().S(`
    <li><input type="checkbox" id="`)
		//line cmd/templates/base.qtpl:34
		qw422016.E().S(item.ID)
		//line cmd/templates/base.qtpl:34
		qw422016.N().S(`"`)
		//line cmd/templates/base.qtpl:34
		if item.Done {
			//line cmd/templates/base.qtpl:34
			qw422016.N().S(` checked="checked"`)
			//line cmd/templates/base.qtpl:34
		}
		//line cmd/templates/base.qtpl:34
		qw422016.N().S(`>`)
		//line cmd/templates/base.qtpl:34
		qw422016.E().S(item.Content)
		//line cmd/templates/base.qtpl:34
		qw422016.N().S(`</input></li>
  `)
		//line cmd/templates/base.qtpl:35
	}
	//line cmd/templates/base.qtpl:35
	qw422016.N().S(`
</ul>
`)
//line cmd/templates/base.qtpl:37
}

//line cmd/templates/base.qtpl:37
func WriteTodo(qq422016 qtio422016.Writer, items []*Item) {
	//line cmd/templates/base.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line cmd/templates/base.qtpl:37
	StreamTodo(qw422016, items)
	//line cmd/templates/base.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line cmd/templates/base.qtpl:37
}

//line cmd/templates/base.qtpl:37
func Todo(items []*Item) string {
	//line cmd/templates/base.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
	//line cmd/templates/base.qtpl:37
	WriteTodo(qb422016, items)
	//line cmd/templates/base.qtpl:37
	qs422016 := string(qb422016.B)
	//line cmd/templates/base.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
	//line cmd/templates/base.qtpl:37
	return qs422016
//line cmd/templates/base.qtpl:37
}
